name: CI/CD - Build & Push Docker Image

on:
  push:
    branches:
      - main  # le pipeline s'exÃ©cute quand tu pushes sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§© RÃ©cupÃ©ration du code
        uses: actions/checkout@v3

      - name: ğŸ Configuration de Python (optionnel pour test Flask)
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: ğŸ”§ Installation des dÃ©pendances (si tu as un requirements.txt)
        run: |
          cd app-cicd
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: ğŸ³ Build de lâ€™image Docker
        run: |
          cd app-cicd
          docker build -t tastasdz/myapp:latest .

      - name: ğŸ”‘ Connexion Ã  Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸš€ Push de lâ€™image sur Docker Hub
        run: |
          docker push tastasdz/myapp:latest
